[versions]
minecraft = "26.3"
fabricLoader = "0.19.5"
fabricApi = "0.160.7+26.3"
fabricLanguageKotlin = "1.14.1+kotlin.2.4.20"
kotlin = "2.4.20"
loom = "1.17-SNAPSHOT"
ksp = "2.3.12"
rimelib = "2.3.5+26.2"
config = "1.0.2"
pods4k = "0.7.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
rimelib = { module = "me.ancientri:rimelib", version.ref = "rimelib" }
config-annotation = { module = "me.ancientri.symbols:config-annotation", version.ref = "config" }
config-processor = { module = "me.ancientri.symbols:config-processor", version.ref = "config" }
pods4k = { module = "com.danrusu.pods4k:pods4k", version.ref = "pods4k" }

[bundles]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }